title: Nafiul's Portfolio
email: your-email@example.com
description: >- 
  Research Portfolio and Professional Profile of Nafiul
baseurl: "" 
url: "https://nafiul9.github.io"
favicon: /assets/images/favicon.ico
repository: nafiul9/nafiul9.github.io

# Navigation
header_pages:
  - index.md
  - publications.md
  - about.md

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Exclude directories and files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore