title: Nafiul's Portfolio
description: Research Portfolio and Professional Profile of Nafiul
baseurl: "" 
url: "https://nafiul9.github.io"

# Theme settings
remote_theme: pages-themes/minimal@v0.2.0

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
