title: Nafiul's Portfolio
email: your-email@example.com
description: >- 
  Research Portfolio and Professional Profile of Nafiul
baseurl: "" # the subpath of your site if applicable
url: "https://nafiul9.github.io"
repository: nafiul9/nafiul9.github.io  # Add this line

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Exclude directories and files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore