title: Nafiul's Portfolio
email: your-email@example.com
description: Research Portfolio and Professional Profile of Nafiul
baseurl: "" 
url: "https://nafiul9.github.io"
favicon: /assets/images/favicon.ico
repository: nafiul9/nafiul9.github.io

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Exclude directories and files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore

# Custom settings
author: Nafiul
github_username: nafiul9
